name: FastAPI CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Reponun kodunu klonla
      uses: actions/checkout@v3

    - name: Python kurulumu
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Bağımlılıkları yükle
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: PYTHONPATH ayarla (app modülünü görsün)
      run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

    - name: Pytest testlerini coverage ile çalıştır
      run: |
        pytest --cov=app --cov-report=term-missing

    - name: Docker kurulumu
      uses: docker/setup-buildx-action@v3

    - name: Docker image oluştur
      run: |
        docker build -t chatgpt-fastapi .
