name: FastAPI CI Pipeline

on:
  push:
    branches: [ main ]  # Veya "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Repo'yu klonla
      uses: actions/checkout@v3

    - name: Python kurulumu
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Bağımlılıkları yükle
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Basit uygulama testi (main.py var mı diye kontrol)
      run: |
        ls app/
        python -c "import app.main"

    - name: Docker image oluştur
      run: |
        docker build -t chatgpt-fastapi .

    # İstersen Docker Hub'a push bölümü de ekleyebiliriz

